### Get SSOT Headers
POST  http://localhost:8080/api/transaction/header HTTP/1.1
Content-Type: application/json

{
    "fileAndPath": "data/Transaction.xlsx",
    "corporateName" : "TestCorp"
}

### Get Auth Token
POST http://localhost:8080/api/transaction/auth HTTP/1.1
Content-Type: application/json

{
    "username": "g2t1",
    "password": "techg@g2t1"
}

### Get Transactions from Excel
POST http://localhost:8080/api/transaction/excel HTTP/1.1
Content-Type: application/json

{
    "fileAndPath": "data/Transaction.xlsx",
    "corporateName" : "TestCorp"
}

### Send Transactions to Sandbox
POST http://localhost:8080/api/transaction/send HTTP/1.1
Content-Type: application/json

{
    "fileAndPath": "data/Transaction.xlsx",
    "corporateName" : "TestCorp",
    "username": "g2t1",
    "password": "techg@g2t1"
}

